srpm:
	dnf -y install desktop-file-utils 'python3-*' cabextract gtk3 psmisc xorg-x11-server-Xephyr xrandr hicolor-icon-theme gnome-desktop3 fdupes libappstream-glib webkit2gtk3 gvfs glx-utils python3-pillow python3-requests mesa-libGL vulkan-loader mesa-dri-drivers mesa-vulkan-drivers
	rpmbuild -ba lutris-unstable.spec
